name: Spelling
on:
  push:
    branches:
      - main
  release:
    types: [published]
  pull_request:
  workflow_dispatch:
jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install -r requirements.txt
      - name: Install Aspell
        run: |
          sudo apt-get install aspell aspell-en
      - name: Install Hunspell
        run: |
          sudo apt-get install hunspell hunspell-en-gb
      - name: codespell
        run: |
          codespell docs
      - name: pyspelling
        run: |
          pyspelling || true
